version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
  redis:
    image: redis
  webpack:
    build: .
    command: bundle exec bin/webpack-dev-server --port 9000
    volumes:
      - .:/shine
    ports:
      - "9000:9000"
  app:
    build: .
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/shine
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - webpack
