version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
  redis:
    image: redis
  app:
    build: .
    command: bash -c "bundle exec foreman start"
    volumes:
      - .:/shine
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
